adminUser:
  password: vault:toothroan/adminUser:password
  username: admin
dashboardUrl: https://dashboard.play-jxaas.live
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:toothroan/pipelineUser:token
  username: cloudbees-ci-cd-play[bot]
prow:
  hmacToken: vault:toothroan/prow:hmacToken
segmentWriteKey: vault:toothroan:segmentWriteKey
